version: "3.8"

services:

  ai-pdf-extractor-service:
    container_name: ai-pdf-extractor
    image: ai-pdf-extractor:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./app:/app
      - /tmp:/tmp
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    shm_size: 32gb
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: streamlit run main.py